### ISSUE TITLE
Fails fetching new version of packman

### ISSUE THREAD

**Issue by comp500** [lyqyd/cc-packman#11]
When I have the pre-namespaces version of packman, fetch downloads the new one then fails. This is because it tries to read the new files but it is still using the old version. Packman needs to be restarted after updating the installer.

**Comment by lyqyd** [comment]
Unfortunately, there's not a whole lot I can do about this issue, if I'm understanding you correctly.  The namespace change is a pretty major breaking change.  For clarity, you're saying that the fetch does manage to grab the new version of everything, but can't reload itself properly, so requires running the program again?

**Comment by comp500** [comment]
Pretty much yes.
