### ISSUE TITLE
Error with new packman

### ISSUE THREAD

**Issue by comp500** [lyqyd/cc-packman#13]
`Could not resolve dependency on main/setup in package demosthenex-turbine`
`packman:83: invalid key to 'next'`

It appears when I try to install, update or remove anything. Fetching works fine.

**Comment by lyqyd** [comment]
Okay, I've worked through this issue and it should be fixed. There were a number of potential contributing causes, all of which should have been resolved.  Run packman fetch twice on any affected systems and you should be clear (packman was not updating the package API like it should have been).

**Comment by comp500** [comment]
Good, will test when I reboot to Windows tomorrow. I could install CCEmuRedux on my linux dualboot but I already have it setup on Windows.

**Comment by comp500** [comment]
Works, tested. One suggestion, in list you should test for when there are no packages installed and say 'there are no packages' etc.
