### ISSUE TITLE
Add package groups

### ISSUE THREAD

**Issue by superaxander** [lyqyd/cc-packman#16]
Groups to install multiple packages at once
example:
```
name = basic-utils
	type = group
		packages = 
			wget
			cat
	category = utilities
	target = /usr/bin
	version = 0.1
	size = 1103
end
```

**Comment by lyqyd** [comment]
This is something I've been considering for a while.  If it were to happen, it would likely be as a download type with no specifications, and list all packages in the group as dependencies.

**Comment by superaxander** [comment]
Ok fair enough

**Comment by lyqyd** [comment]
This functionality was added in commit c4ec75591ccb327a26f7f01e83e7bffb065c5fd2.
