### ISSUE TITLE
Add optional restrictions

### ISSUE THREAD

**Issue by apemanzilla** [lyqyd/cc-packman#20]
Would it be possible to add restrictions for packages to packman? For example, add a field named "restrict" where a developer can specify an api or basic statement that must evaluate to true to allow the package to be installed. For example, having "restrict = turtle" would mean the package could only be installed to turtles.

**Comment by lyqyd** [comment]
That's an interesting idea, actually.  I'll have to give this some thought.

**Comment by infogulch** [comment]
Could this be implemented as a failure mode in the setup script? I.e. uninstall if the setup script fails?

**Comment by lyqyd** [comment]
Hmm, an interesting thought.  How would the script declare that it's failed, though?

Of course, if there was a package that would only successfully install to turtles, it would definitely be better to have it fail as soon as possible, so that non-turtle computers could avoid downloading the files in the package.

**Comment by infogulch** [comment]
Yeah a turtle-specific script would be the most obvious restriction, but it
would be a shame to preclude other possible restrictions to hard code the
turtle restriction. E.g. what about a script that needs http access to a
specific domain not typically listed in the whitelist?

And script files are usually pretty small, right? I'd s be surprised if
there are many scripts over a couple dozen kb, which is almost negligible.

About signaling the restriction, what if the setup script's install
function returned an error?

**Comment by apemanzilla** [comment]
@lyqyd maybe a message after packman finishes running along the lines of "Package X could not be installed: insert reason here"

**Comment by lyqyd** [comment]
Hmm, these are good thoughts.  An error message captured from the setup script is probably not a bad idea.  I'll look at this in more detail this weekend.  Hopefully, it shouldn't be too hairy to implement.

**Comment by lyqyd** [comment]
Okay, I've added this feature.  If a package includes a setup script, and that setup script throws an error when it's run, the package will be removed.  Give it a shot and let me know if you have any issues with the feature.

Thanks for the suggestion!

**Comment by apemanzilla** [comment]
Thanks, I'll look into it when I get a chance.
