### ISSUE TITLE
Virtual package support?

### ISSUE THREAD

**Issue by ThePhoenix47** [lyqyd/cc-packman#25]
Could you add support for some kind of virtual packages, I mean packages without any files, so they just load their dependencies, for example you have a program suite, you add all programs as own packages and then create a virtual package loading them all?

**Comment by lyqyd** [comment]
Is there a significant difference between what you're suggesting and the [meta package type](https://github.com/lyqyd/cc-packman#612---download-type)?

**Comment by ThePhoenix47** [comment]
Whoopsy, seems I didn't see that part. That was what I meant, so this can be closed.
