### ISSUE TITLE
Add support for help files

### ISSUE THREAD

**Issue by apemanzilla** [lyqyd/cc-packman#27]
One feature that I think would be nice would be built-in support for help files. Maybe add a folder `/usr/help` which is added with `help.setPath`, and then packages can specify links to help files that will be downloaded there.

Then, users can simply use the `help` command to get help on packages installed with packman.

**Comment by lyqyd** [comment]
This isn't a bad idea, but there are cases where a single package would want to specify multiple help files.  One workaround I can think of would be to set up a second package containing the help file(s), and specify it as a dependency of the package they go with.  The help files package could target the help files folder, and perhaps the easy-shell script could add /usr/help to the help path.

Thoughts?

**Comment by apemanzilla** [comment]
Yeah, /usr/help is probably the best solution, or /usr/docs.

While we're on the topic of adding stuff to easy-shell, would it be possible to add a folder of scripts that are run on startup? /usr/init? I can make this into a separate issue if necessary.

**Comment by lyqyd** [comment]
I'm a little reluctant to venture into startup sequence management.  There are a lot of things that are difficult to account for, most especially when pre-existing startup files come into play.  I'm not sure adding a folder to autorun scripts from is really within the scope of easy-shell (or even packman, for that matter).  I'd have to think about that one a bit more.

**Comment by apemanzilla** [comment]
Alright, that's a fair point. I've been struggling to come up with a way to package 'daemons' per se that can automatically run in the background on startup.

**Comment by lyqyd** [comment]
I've now had multiple requests to include help files with packages in one way or another. I think that including help files is a good idea, and definitely worth pursuing. If a help files system is to be added, I think it needs to meet the following criteria:

* All help files from all packages should be placed in one directory.
* Each package's help files should be downloaded using the same download type specification system as the package's main files.
* The help file directory should be added to the help file path by easy-shell.
* Including help files with packages is optional.
* Packages will own their help files, so the help files are removed when the package is removed.

I don't want to build in a help file system if it's just going to be fragmented across different directories, so help files will have to all end up in one directory (and I'd suggest /usr/help).

Thoughts, anyone?

**Comment by apemanzilla** [comment]
Sounds good to me.

**Comment by Wilma456** [comment]
Thats a good plan. You do not need more than one help file per package (You have somtimes write from multiple files). Helpfiles just need a few Information:
-what does the programm do
-Are there Args?
-Why report bugs
-Where is the author
-What license
-A API documention (for apis)
A single helpfile is enough for this.

**Comment by Wilma456** [comment]
I have found a methode, to add  help files. First I show the old package:
name = example
  type = raw
   url = URL of your program
   filename = example
  category = example
  dependencies = none
  target = /usr/bin
  version = 1.0.0
  size = 100
end
Now I show this package with added a help file:
name = example
  type = raw
   url = URL of your program
   filename = usr/bin/example
  category = example
  dependencies = none
  target = /
  setup = rom/programs/http/wget Url of your helpfile /usr/help/example
  cleanup = rom/programs/delete /usr/help/example
  version = 1.0.0
  size = 110
end
This works great and I use it with my programs. The only thing, what you must do is to run help.setPath( help.path() .. ":/usr/help") at startup. What do you think about my idea?

**Comment by lyqyd** [comment]
That relies on the (invalid) assumption that only a single help file would ever be necessary for a given package. In fact, packages like LyqydOS contain multiple programs that would each need their own help files. I will work on adding an official help files mechanism soon, that will support both single- and multiple-file help file downloads.

I'm also considering having help file downloads be a configurable feature.  Users would be able to disable help file downloads, though they would be enabled by default. I'd probably also need to include a separate help file installation command that would install *just* the help files for specified packages. I'm thinking `install-help`, `update-help` and `remove-help` for the command keywords, to match `install`, `update`, and `remove`. These would only be necessary to manually manipulate help files, and default settings would simply install and remove the help files with the packages they're attached to.

**Comment by aaronmallen** [comment]
+1

**Comment by lyqyd** [comment]
I've added initial support for help files in 5e07fac just now, but they are not yet managed automatically. I need to update the documentation to reflect the ability to specify help file downloads. They are currently all forced to install under `/etc/help/repo-name/package-name`.

Next steps include adding the `install-help`, `upgrade-help` and `remove-help` commands to the list of commands and providing documentation on how to create help download entries in your package listings. And lots and lots of testing.

**Comment by lyqyd** [comment]
This should be resolved with 94f4926. Please let me know if you run into any issues with help files.

Help file management is disabled by default, but `packman bootstrap` creates `/etc/packman/packman.conf` to allow easy editing of this setting. Any future configuration options will be found in that file as well.
