### ISSUE TITLE
What about a "community" repo?

### ISSUE THREAD

**Issue by Admicos** [lyqyd/cc-packman#37]
I think it could be used to host the commonly used APIs that don't have a package for the programs that depend on them, or for the people that don't want to have a repo for them and just want to put a package or two.

What do you guys think about it?

**Comment by lyqyd** [comment]
Which APIs would end up in there?  Who would be in charge of determining which version of each API should be available? Who decides whether an API is worthy of inclusion in the community repo?

**Comment by Admicos** [comment]
> Which APIs would end up in there?
Actually, i thought it as more of a "if you need it and it doesnt have a package, add here" kinda thing, so probably ones people will actually use in their packages

> Who would be in charge of determining which version of each API should be available?
Unless it has something wrong with it, the latest version will be available. 

> Who decides whether an API is worthy of inclusion in the community repo?
I would say "no one" since (in the first answer) i said "i thought it as more of a "if you need it and it doesnt have a package, add here" kinda thing" so yeah.

**Comment by lyqyd** [comment]
If there's an API that someone is wanting to use for one of their packages, the usual thing to do would be to set it up as another package and list that package as a dependency of the first one. Other repo maintainers could then set up that package as a dependency for their program if they choose to use it as well.

Well, a "community" repo would have to be hosted someplace, so someone would have to approve additions/removals on it.

I guess I'm just having trouble seeing the benefits of a single large repo of whatever anyone ever wanted included, when anyone and everyone is free to add their own repo for their software and maintain it however they see fit.

**Comment by Admicos** [comment]
> If there's an API that someone is wanting to use for one of their packages, the usual thing to do would be to set it up as another package and list that package as a dependency of the first one. Other repo maintainers could then set up that package as a dependency for their program if they choose to use it as well.

Yeah, after thinking about this a little bit more, this seems like the best option.
