### ISSUE TITLE
Add a "list of urls" download type. 

### ISSUE THREAD

**Issue by Admicos** [lyqyd/cc-packman#39]
I am currently using[ a very hacky program ](https://github.com/Admicos/cc-packman-repo/blob/master/pachax/pachax.lua)i made to do this, but it would be pretty useful if it was integrated to packman itself, as currently downloading multiple files are only limited to repositories

Packman will get a file which has the following format: 

    https://example.com/file1 /file1
    https://example.com/file2 /file2
    https://example.com/file3 /file3

And it'll save the files (possibly relative to the target folder) in the place after the seperating space.

**Comment by lyqyd** [comment]
I could see some value in such an option.  If it were to be implemented, it would take the following form:

    type: raw-multi
        file1 http://example.com/file1
        file2 http://example.com/file1

Where the first non-space characters are the filename and the remainder of the line is the URL to fetch. Files downloaded this way would be placed as normal according to the rules of raw download file placement, that is, in /usr/bin or wherever the target directory is.

I'm not a huge fan of the idea; I'd really prefer to encourage people to put things in repositories, as there are important advantages, such as incremental updating (downloading from a github repository means that when there's an update, packman only needs to download changed files). That hacky way of implementing this does seem like an unnecessarily complex workaround.

I think that this is probably going to be worth implementing, so I'll look into it as I have time.
