### ISSUE TITLE
Push into CC

### ISSUE THREAD

**Issue by D0han** [lyqyd/cc-packman#4]
Polish and push to dan200.

**Comment by sci4me** [comment]
I would be against this myself.....

**Comment by lyqyd** [comment]
Why?

**Comment by sci4me** [comment]
I just wouldn't want CC to have one by default. No particular reason I suppose... personal preference.

**Comment by MineRobber9000** [comment]
I agree with sci4me. ComputerCraft users can easily install packman if they want to. I guess my reason is that I don't believe that people should be forced to have packman if some of them will never use it.

**Comment by aaronmallen** [comment]
I have to agree with @sci4me and @MineRobber9000 here... if dan200 wanted someone to monopolize the package management market, he likely would have included one himself...

**Comment by lyqyd** [comment]
It's unlikely to happen anyway. This is the sort of thing that would have to come from dan200, if he were interested in including it. I'd be open to that, but I'm not going to push him about it.

Closed.
