### ISSUE TITLE
Error when installing packman from pastebin

### ISSUE THREAD

**Issue by drewcassidy** [lyqyd/cc-packman#41]
I'm getting an error that makes packman completely unusable

installing packman from pastebin results in this error halfway down the repository fetch messages, and then every time i try to run packman after that. It also never installs easy-shell because of this. all my computers that had packman installed before still work, however. 
<img width="1280" alt="screen shot 2016-08-27 at 1 03 54 pm" src="https://cloud.githubusercontent.com/assets/3837797/18029998/0d4185ac-6c5d-11e6-8558-84d4f13dbb4f.png">
<img width="1280" alt="screen shot 2016-08-27 at 1 43 15 pm" src="https://cloud.githubusercontent.com/assets/3837797/18029999/0fbbd4c2-6c5d-11e6-9a05-ca59b173d6f0.png">

I suspect this is because of the recent addition of #38 being done incorrectly

**Comment by drewcassidy** [comment]
Oh, and this is in computercraft 1.75 in FTB Infinity Evolved 2.6.0, Minecraft 1.7.10 from a multiplayer server

**Comment by lyqyd** [comment]
The yellow line immediately above the error shows that the "h4x0rz" repository had a mis-specified package. Since that issue has been corrected, you should be able to install packman successfully now. I'll look into making packman more resilient against these sorts of issues.
