### ISSUE TITLE
Run Programs out of the target as setup or cleanup

### ISSUE THREAD

**Issue by Wilma456** [lyqyd/cc-packman#43]
I want to give my programs a manpage. And theres no thing in packman to do that (you have not accepted my pull request) so I have the idea to run wget as setup and delete as cleanup.But I can only run Programs, who are in the target of the package. Is there any way to run Programs outside of the target .I know. that I can make a second package or write a script, but thats my favourite possibility.

**Comment by lyqyd** [comment]
Your best bet right now is to make a second package.

There's another open issue that has the beginning of a discussion about including help files with packages, and I'm going to go more in-depth on my thoughts on the matter over there. You're welcome to continue the dicussion about help files / man pages in #27.
