### ISSUE TITLE
Setup not called on update

### ISSUE THREAD

**Issue by aaronmallen** [lyqyd/cc-packman#50]
Currently packman will not execute the setup script on update... I can see how executing this would be problematic, but perhaps we can include an update property for packages to run on update.

**Comment by lyqyd** [comment]
Some package download types actually perform a full remove-reinstall cycle when updating. I'll have to review which ones do what. An update field is something I'd considered in the past, so I'll have to work through the design and implications of implementing it again. Good suggestion!

**Comment by lyqyd** [comment]
This is added.
