### ISSUE TITLE
Version String Support

### ISSUE THREAD

**Issue by lyqyd** [lyqyd/cc-packman#51]
Remove old tonumber() version comparison and replace it with an iterative tonumber() comparison to check each period-separated component of the version string. Non-numeric characters in version strings will continue to be unsupported.

**Comment by aaronmallen** [comment]
:+1:

**Comment by lyqyd** [comment]
Huh. Looks like you can use [whatever you want](https://github.com/lyqyd/cc-packman/blob/master/packman#L463) to use for version strings already. I'll have to update the documentation.

**Comment by aaronmallen** [comment]
@lyqyd so to clarify I can pass a semver friendly string?

**Comment by lyqyd** [comment]
Yes.
