### ISSUE TITLE
Port for open computers

### ISSUE THREAD

**Issue by aaronmallen** [lyqyd/cc-packman#53]
Direwolf20 just released his new pack... it looks like there's no CC but he does have open computers... It looks like it shares a lot of the same functionality as CC but there are some small differences (i.e. [internet.request()](http://ocdoc.cil.li/api:internet) vs http.get())

The scope of this feature request is to create either a seperate port of packman for [Open Computers](http://ocdoc.cil.li/) or refactor packman in a way that it can handle both.

**Comment by lyqyd** [comment]
It looks like OC actually has an [official package management system](http://ocdoc.cil.li/tutorial:program:oppm). I don't particularly use OC personally, so creating a port isn't something I'm likely to invest my free time in to. Packman is licensed under MIT, so if you're set on using it in OC (bearing in mind that most packages won't work), you could always fork it and create a port.

**Comment by aaronmallen** [comment]
didn't even think about the packages being incompatible (derp)
