### ISSUE TITLE
New CC versions with package table interferes with the package API

### ISSUE THREAD

**Issue by cntkillme** [lyqyd/cc-packman#60]
Since the package table has been implemented in later versions of CC, packman assumes that its own package library was loaded because the package global exists (see loadPackageAPI function in packman script).

A simple solution would just be to rename it however I'm not sure if programs from other projects rely on the package API from packman.

**Comment by lyqyd** [comment]
Solved with #62. I've left the package API entry in the package list, but users should have no problem uninstalling that package after running `packman fetch update`. New installations will only install the backpack API (the renamed package API). Other projects will have to rename their calls into the package API, unfortunately. Hopefully the new name is sufficiently unique that they will only have to rename it this one time.
