### ISSUE TITLE
Add your own repo

### ISSUE THREAD

**Issue by WilcoDW** [lyqyd/cc-packman#64]
Besides the official repos I think alot of people would like to use the really nice utility to manage their own scripts so they can be easily installed on other computers. 

`packman repo add <url>`
The url can point to an actual repository, a list of repos or a pastebin code with repos

`packman repo remove <name / url>`
Does the opposite, removes a repo from the local list of repos

**Comment by Wilma456** [comment]
Take a look at Minepack (http://www.computercraft.info/forums2/index.php?/topic/28924-minepack-a-packman-compatible-package-manager/). It is full compatible with Packman and has this feature.

**Comment by lyqyd** [comment]
I've been meaning to add this feature for a while!  4d4d38d adds support for this via `/etc/custom-repolist`, which uses the same format as `/etc/repolist`, but won't be replaced each time you run `packman fetch`.
