### ISSUE TITLE
lyqyd/inv-inventory appears to also require lyqyd/configuration

### ISSUE THREAD

**Issue by Johnystar** [lyqyd/cc-packman#75]
![image](https://user-images.githubusercontent.com/29976879/142721786-b1b9dfa8-22a8-45d6-afaa-7814ac8279d5.png)
``inventory`` command doesn't work (**without** ``lyqyd/configuration`` installed)

![image](https://user-images.githubusercontent.com/29976879/142721843-aea8d524-cf21-4cb0-9ae8-453df81142a8.png)
``inventory`` command seems to work (**with** ``lyqyd/configuration`` installed)

**Comment by Bencor29** [comment]
Hey,

You're right, there's a missing dependency in the package list.
I made a PR (#76) to patch this.

**Comment by lyqyd** [comment]
Thanks for the report. I'll review and likely merge the pull request.

I can't promise that the inventory package will do anything useful, though! It was a WIP project when I last touched it. I think I had the storage itself working fairly well, but the rest of the system to make it user friendly or able to interact with other bits of automation was nowhere near complete.
