### ISSUE TITLE
"Could not resolve dependency on admicos/ghv in package jakobdev/tarlib-doc"

### ISSUE THREAD

**Issue by foopis23** [lyqyd/cc-packman#77]
It seems #73 removes admicos from the repolist, but another repo in the default list depends on it... It seems to be blocking me from installing any other packages. 
![image](https://user-images.githubusercontent.com/10903307/143687914-cf4800a7-2342-4b01-82d8-a54b130a9ef7.png)

**Comment by foopis23** [comment]
This issue can be temporarily worked around by:
1. Edit `/etc/repolist` and removing the jakobdev entry
2. Delete the file /etc/repositories/jakobdev

**Comment by lyqyd** [comment]
Thank you for the issue report. It appears that the packages listed above no longer depend on admicos/ghv, so I am closing this issue as resolved.
